Controllers/SpedizioniController.cs
using AgenziaSpedizioni.Dati;
using AgenziaSpedizioni.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AgenziaSpedizioni.Controllers
{
    public class SpedizioniController : Controller
    {
        private MyDbContext db = new MyDbContext();

        // GET: Spedizioni
        public ActionResult Index()
        {
            return View(db.Spedizioni.ToList());
        }

        // GET: Spedizioni/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Spedizione spedizione = db.Spedizioni.Find(id);
            if (spedizione == null)
            {
                return HttpNotFound();
            }
            return View(spedizione);
        }

        // GET: Spedizioni/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Spedizioni/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDSpedizione,DataSpedizione,Peso,CittaDestinataria,IndirizzoDestinatario,NomeDestinatario,CostoSpedizione,DataConsegnaPrevista")] Spedizione spedizione)
        {
            if (ModelState.IsValid)
            {
                db.Spedizioni.Add(spedizione);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(spedizione);
        }

        // GET: Spedizioni/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Spedizione spedizione = db.Spedizioni.Find(id);
            if (spedizione == null)
            {
                return HttpNotFound();
            }
            return View(spedizione);
        }

        // POST: Spedizioni/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDSpedizione,DataSpedizione,Peso,CittaDestinataria,IndirizzoDestinatario,NomeDestinatario,CostoSpedizione,DataConsegnaPrevista")] Spedizione spedizione)
        {
            if (ModelState.IsValid)
            {
                db.Entry(spedizione).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(spedizione);
        }

        // GET: Spedizioni/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Spedizione spedizione = db.Spedizioni.Find(id);
            if (spedizione == null)
            {
                return HttpNotFound();
            }
            return View(spedizione);
        }

        // POST: Spedizioni/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Spedizione spedizione = db.Spedizioni.Find(id);
            db.Spedizioni.Remove(spedizione);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Spedizioni/Create.cshtml
@model AgenziaSpedizioni.Models.Spedizione

@{
    ViewBag.Title = "Crea Nuova Spedizione";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Create", "Spedizioni", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.DataSpedizione, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataSpedizione, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DataSpedizione, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Peso, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CittaDestinataria, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CittaDestinataria, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CittaDestinataria, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IndirizzoDestinatario, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IndirizzoDestinatario, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IndirizzoDestinatario, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NomeDestinatario, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NomeDestinatario, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NomeDestinatario, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CostoSpedizione, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CostoSpedizione, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CostoSpedizione, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DataConsegnaPrevista, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataConsegnaPrevista, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DataConsegnaPrevista, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crea" class="btn btn-default" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Torna all'elenco", "Index")
</div>

Views/Spedizioni/Delete.cshtml
@model AgenziaSpedizioni.Models.Spedizione

@{
    ViewBag.Title = "Elimina Spedizione";
}

<h2>@ViewBag.Title</h2>

<h3>Sei sicuro di voler eliminare questa spedizione?</h3>

<div>
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.DataSpedizione)</dt>
        <dd>@Html.DisplayFor(model => model.DataSpedizione)</dd>

        <dt>@Html.DisplayNameFor(model => model.Peso)</dt>
        <dd>@Html.DisplayFor(model => model.Peso)</dd>

        <dt>@Html.DisplayNameFor(model => model.CittaDestinataria)</dt>
        <dd>@Html.DisplayFor(model => model.CittaDestinataria)</dd>

        <dt>@Html.DisplayNameFor(model => model.IndirizzoDestinatario)</dt>
        <dd>@Html.DisplayFor(model => model.IndirizzoDestinatario)</dd>

        <dt>@Html.DisplayNameFor(model => model.NomeDestinatario)</dt>
        <dd>@Html.DisplayFor(model => model.NomeDestinatario)</dd>

        <dt>@Html.DisplayNameFor(model => model.CostoSpedizione)</dt>
        <dd>@Html.DisplayFor(model => model.CostoSpedizione)</dd>

        <dt>@Html.DisplayNameFor(model => model.DataConsegnaPrevista)</dt>
        <dd>@Html.DisplayFor(model => model.DataConsegnaPrevista)</dd>
    </dl>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions">
        <input type="submit" value="Elimina" class="btn btn-danger" /> |
        @Html.ActionLink("Annulla", "Index")
    </div>
}

Views/Spedizioni/Details.cshtml
@model AgenziaSpedizioni.Models.Spedizione

@{
    ViewBag.Title = "Dettagli Spedizione";
}

<h2>@ViewBag.Title</h2>

<div class="details">
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.DataSpedizione)</dt>
        <dd>@Html.DisplayFor(model => model.DataSpedizione)</dd>

        <dt>@Html.DisplayNameFor(model => model.Peso)</dt>
        <dd>@Html.DisplayFor(model => model.Peso)</dd>

        <dt>@Html.DisplayNameFor(model => model.CittaDestinataria)</dt>
        <dd>@Html.DisplayFor(model => model.CittaDestinataria)</dd>

        <dt>@Html.DisplayNameFor(model => model.IndirizzoDestinatario)</dt>
        <dd>@Html.DisplayFor(model => model.IndirizzoDestinatario)</dd>

        <dt>@Html.DisplayNameFor(model => model.NomeDestinatario)</dt>
        <dd>@Html.DisplayFor(model => model.NomeDestinatario)</dd>

        <dt>@Html.DisplayNameFor(model => model.CostoSpedizione)</dt>
        <dd>@Html.DisplayFor(model => model.CostoSpedizione)</dd>

        <dt>@Html.DisplayNameFor(model => model.DataConsegnaPrevista)</dt>
        <dd>@Html.DisplayFor(model => model.DataConsegnaPrevista)</dd>
    </dl>
</div>

<p>
    @Html.ActionLink("Modifica", "Edit", new { id = Model.IDSpedizione }) |
    @Html.ActionLink("Torna all'elenco", "Index")
</p>

Views/Spedizioni/Edit.cshtml
@model AgenziaSpedizioni.Models.Spedizione

@{
    ViewBag.Title = "Modifica Spedizione";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "Spedizioni", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.IDSpedizione)

    <div class="form-group">
        @Html.LabelFor(model => model.DataSpedizione, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataSpedizione, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DataSpedizione, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Peso, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CittaDestinataria, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CittaDestinataria, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CittaDestinataria, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IndirizzoDestinatario, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IndirizzoDestinatario, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IndirizzoDestinatario, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NomeDestinatario, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NomeDestinatario, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NomeDestinatario, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CostoSpedizione, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CostoSpedizione, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CostoSpedizione, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DataConsegnaPrevista, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataConsegnaPrevista, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DataConsegnaPrevista, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salva" class="btn btn-default" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Torna all'elenco", "Index")
</div>

Views/Spedizioni/Index.cshtml
@model IEnumerable<AgenziaSpedizioni.Models.Spedizione>

<h2>Spedizioni</h2>

<p>
    @Html.ActionLink("Crea Nuova Spedizione", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DataSpedizione)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CittaDestinataria)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomeDestinatario)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DataSpedizione)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CittaDestinataria)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NomeDestinatario)
            </td>
            <td>
                @Html.ActionLink("Dettagli", "Details", new { id = item.IDSpedizione }) |
                @Html.ActionLink("Modifica", "Edit", new { id = item.IDSpedizione }) |
                @Html.ActionLink("Elimina", "Delete", new { id = item.IDSpedizione })
            </td>
        </tr>
    }

</table>